// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_proxy/chat.proto

package stream_gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyChatGPTStreamReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyChatGPTStreamReq) Reset()         { *m = ProxyChatGPTStreamReq{} }
func (m *ProxyChatGPTStreamReq) String() string { return proto.CompactTextString(m) }
func (*ProxyChatGPTStreamReq) ProtoMessage()    {}
func (*ProxyChatGPTStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3446fd65c25f44e5, []int{0}
}

func (m *ProxyChatGPTStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyChatGPTStreamReq.Unmarshal(m, b)
}
func (m *ProxyChatGPTStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyChatGPTStreamReq.Marshal(b, m, deterministic)
}
func (m *ProxyChatGPTStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyChatGPTStreamReq.Merge(m, src)
}
func (m *ProxyChatGPTStreamReq) XXX_Size() int {
	return xxx_messageInfo_ProxyChatGPTStreamReq.Size(m)
}
func (m *ProxyChatGPTStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyChatGPTStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyChatGPTStreamReq proto.InternalMessageInfo

func (m *ProxyChatGPTStreamReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProxyChatGPTStreamReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ProxyChatGPTStreamResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AudioContent         string   `protobuf:"bytes,3,opt,name=audioContent,proto3" json:"audioContent,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyChatGPTStreamResp) Reset()         { *m = ProxyChatGPTStreamResp{} }
func (m *ProxyChatGPTStreamResp) String() string { return proto.CompactTextString(m) }
func (*ProxyChatGPTStreamResp) ProtoMessage()    {}
func (*ProxyChatGPTStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3446fd65c25f44e5, []int{1}
}

func (m *ProxyChatGPTStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyChatGPTStreamResp.Unmarshal(m, b)
}
func (m *ProxyChatGPTStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyChatGPTStreamResp.Marshal(b, m, deterministic)
}
func (m *ProxyChatGPTStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyChatGPTStreamResp.Merge(m, src)
}
func (m *ProxyChatGPTStreamResp) XXX_Size() int {
	return xxx_messageInfo_ProxyChatGPTStreamResp.Size(m)
}
func (m *ProxyChatGPTStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyChatGPTStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyChatGPTStreamResp proto.InternalMessageInfo

func (m *ProxyChatGPTStreamResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProxyChatGPTStreamResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ProxyChatGPTStreamResp) GetAudioContent() string {
	if m != nil {
		return m.AudioContent
	}
	return ""
}

func (m *ProxyChatGPTStreamResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyChatGPTStreamReq)(nil), "stream_proxy.ProxyChatGPTStreamReq")
	proto.RegisterType((*ProxyChatGPTStreamResp)(nil), "stream_proxy.ProxyChatGPTStreamResp")
}

func init() { proto.RegisterFile("stream_proxy/chat.proto", fileDescriptor_3446fd65c25f44e5) }

var fileDescriptor_3446fd65c25f44e5 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2e, 0x29, 0x4a,
	0x4d, 0xcc, 0x8d, 0x2f, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x4f, 0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x41, 0x96, 0x50, 0x72, 0xe4, 0x12, 0x0d, 0x00, 0x31, 0x9c, 0x33,
	0x12, 0x4b, 0xdc, 0x03, 0x42, 0x82, 0xc1, 0x72, 0x41, 0xa9, 0x85, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x12, 0x5c, 0xec, 0xc9,
	0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x12, 0x4c, 0x60, 0x41, 0x18, 0x57, 0xa9, 0x82, 0x4b, 0x0c,
	0x9b, 0x11, 0xc5, 0x05, 0xc4, 0x9b, 0x21, 0xa4, 0xc4, 0xc5, 0x93, 0x58, 0x9a, 0x92, 0x99, 0xef,
	0x0c, 0x95, 0x66, 0x06, 0x4b, 0xa3, 0x88, 0x09, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5, 0x48, 0xb0,
	0x80, 0xa5, 0x40, 0x4c, 0xa3, 0x4a, 0x2e, 0x21, 0x88, 0x6d, 0x60, 0xfb, 0x83, 0x53, 0x8b, 0xca,
	0x32, 0x93, 0x53, 0x85, 0x92, 0xb9, 0x84, 0x30, 0xdd, 0x23, 0xa4, 0xac, 0x87, 0xec, 0x6f, 0x3d,
	0xac, 0x9e, 0x96, 0x52, 0x21, 0xac, 0xa8, 0xb8, 0x40, 0x83, 0xd1, 0x80, 0xd1, 0xc9, 0x36, 0xca,
	0x3a, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x38, 0xd4, 0x37, 0x20,
	0xb1, 0x34, 0x47, 0xbf, 0xb8, 0x20, 0x35, 0x31, 0x3b, 0x3d, 0x1e, 0x1c, 0xd0, 0xfa, 0x60, 0x32,
	0xa9, 0x34, 0xcd, 0x58, 0xaf, 0x20, 0x49, 0x1f, 0x6a, 0x6e, 0x7a, 0x62, 0x49, 0x6a, 0x79, 0x62,
	0x65, 0x12, 0x1b, 0x58, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x57, 0xd7, 0x2c, 0xa6, 0xa6,
	0x01, 0x00, 0x00,
}
